# This file is a tweak for niri:
# Make it possible to intercept single modifier 'Super' keybinding.
# It could be useful for starting launcher.
#
# Future notice:
# Mind to remove this tweak after the following niri PR will be merged:
# - https://github.com/niri-wm/niri/pull/2456
# - corresponding issue: https://github.com/niri-wm/niri/issues/605

# Setup:
# Install keyd (`sudo pacman -S keyd`)
# Enable keyd service: (`sudo systemctl enable keyd --now`)
# Use `sudo keyd reload` for config hot-reload
# Link this file: "sudo ln -s $(pwd)/niri/keyd.conf /etc/keyd/keyd.conf"

[ids]

# This seems to provide a way to match to different inputs (* matches to all)
# To find ids, can press keys after using: sudo keyd monitor
# Seems able to catch non-keyboard events too...?
*

[global]

# Holding a key for longer than this (in ms) won't count as a tap
overload_tap_timeout = 300;

[main]

# Make super key tap act like a super+0 combo
leftmeta = overload(meta, macro(leftmeta+0))
# Syntax seems to be:
#   key_being_altered = overload(behavior when held, behavior when tapped)

# Make the 'right menu' key act like the super key
compose = overload(meta, macro(leftmeta+0))

